### PR TITLE
Create files

### PR DESCRIPTION
**Pull request by Berucan**
I included an index file with a header element,  style file to add styling to it and also modified README file, add  project description, author social network details.

### CODE REVIEW

**Review by ReshyResh — CHANGES_REQUESTED** [review]
# Hi @Berucan , 

### You did a great job so far!
  - ✔Meaningful PR and commit messages.
  - ✔Correct use of Gitflow.
  - ✔Correct linters setup.

#### There are some issues that you still need to work on to go to the next project but you are almost there!


## Required Changes ♻️
You added the `test.md` file and `node_modules` folder to the `.gitignore` file after uploading them, which means they weren't ignored by Git since the beginning.
The files in the `.gitignore` file should be ignored since the beginning and not be uploaded at all, especially the `node_modules` folder which installs the local dependencies on your machine.

- [x] Please make sure to actually ignore these files in your remote repo. Since you already pushed them, make another commit where you delete them, push it online, then make sure on the next commits Git is ignoring these files and not uploading them.


#### Cheers and Happy coding!👏👏👏

----

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by Amrhub — CHANGES_REQUESTED** [review]
Hi @Berucan, 👋🏻 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
_Check the comments under the review._

You could notice the folder `node_modules` is still on your local that's because git kept the file in the tracking list using cache so in order to lose track of this folder or file you could use this command in your terminal
```shell
git rm cached <filename> -r
```
-r is a flag that tells git to remove it as well please use this in the folder/files requested from previous code reviewer and make sure it's not on your repository anymore then resubmit it for another code reviewer 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Berucan** [comment]
##  Hi @ReshyResh @Amrhub 
I apologise for not being able to ignore the .gitignore file from the start but i promise to do so for all the upcoming projects going forward.  In my last commit i ignored them as requested now i hope that my last pull request will be reviewed and approved.

**Review by andersonlebon — APPROVED** [review]
## Hi @Berucan 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 :clap: :clap: :100: 

nodding-yes

## Optional suggestions
- [ ] Kindly Check the comments under the review._
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Pull request merged**
